// <auto-generated />
using System;
using HogwartsHomework.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HogwartsHomework.Migrations
{
    [DbContext(typeof(HogwartsDbContext))]
    [Migration("20260824201725_AddPatronusToWizards")]
    partial class AddPatronusToWizards
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HogwartsHomework.Models.Wand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoreMaterial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<string>("Wood")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Wands");
                });

            modelBuilder.Entity("HogwartsHomework.Models.Wizard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EnrollmentYear")
                        .HasColumnType("int");

                    b.Property<string>("House")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Patronus")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("WandId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WandId")
                        .IsUnique()
                        .HasFilter("[WandId] IS NOT NULL");

                    b.ToTable("Wizards");
                });

            modelBuilder.Entity("HogwartsHomework.Models.Wizard", b =>
                {
                    b.HasOne("HogwartsHomework.Models.Wand", "Wand")
                        .WithOne("Wizard")
                        .HasForeignKey("HogwartsHomework.Models.Wizard", "WandId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Wand");
                });

            modelBuilder.Entity("HogwartsHomework.Models.Wand", b =>
                {
                    b.Navigation("Wizard");
                });
#pragma warning restore 612, 618
        }
    }
}
